# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class EnrollmentGroup(Model):
    """Enrollment group record.

    All required parameters must be populated in order to send to Azure.

    :param enrollment_group_id: Required. Enrollment Group ID.
    :type enrollment_group_id: str
    :param attestation: Required. Attestation method used by the device.
    :type attestation: ~serviceswagger.models.AttestationMechanism
    :param iot_hub_host_name: The Iot Hub host name.
    :type iot_hub_host_name: str
    :param initial_twin: Initial device twin.
    :type initial_twin: ~serviceswagger.models.InitialTwin
    :param etag: The entity tag associated with the resource.
    :type etag: str
    :param provisioning_status: The provisioning status. Possible values
     include: 'enabled', 'disabled'. Default value: "enabled" .
    :type provisioning_status: str or ~serviceswagger.models.enum
    :param created_date_time_utc: The DateTime this resource was created.
    :type created_date_time_utc: datetime
    :param last_updated_date_time_utc: The DateTime this resource was last
     updated.
    :type last_updated_date_time_utc: datetime
    """

    _validation = {
        'enrollment_group_id': {'required': True},
        'attestation': {'required': True},
    }

    _attribute_map = {
        'enrollment_group_id': {'key': 'enrollmentGroupId', 'type': 'str'},
        'attestation': {'key': 'attestation', 'type': 'AttestationMechanism'},
        'iot_hub_host_name': {'key': 'iotHubHostName', 'type': 'str'},
        'initial_twin': {'key': 'initialTwin', 'type': 'InitialTwin'},
        'etag': {'key': 'etag', 'type': 'str'},
        'provisioning_status': {'key': 'provisioningStatus', 'type': 'str'},
        'created_date_time_utc': {'key': 'createdDateTimeUtc', 'type': 'iso-8601'},
        'last_updated_date_time_utc': {'key': 'lastUpdatedDateTimeUtc', 'type': 'iso-8601'},
    }

    def __init__(self, **kwargs):
        super(EnrollmentGroup, self).__init__(**kwargs)
        self.enrollment_group_id = kwargs.get('enrollment_group_id', None)
        self.attestation = kwargs.get('attestation', None)
        self.iot_hub_host_name = kwargs.get('iot_hub_host_name', None)
        self.initial_twin = kwargs.get('initial_twin', None)
        self.etag = kwargs.get('etag', None)
        self.provisioning_status = kwargs.get('provisioning_status', "enabled")
        self.created_date_time_utc = kwargs.get('created_date_time_utc', None)
        self.last_updated_date_time_utc = kwargs.get('last_updated_date_time_utc', None)
