# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IndividualEnrollment(Model):
    """The device enrollment record.

    All required parameters must be populated in order to send to Azure.

    :param capabilities: Capabilities of the device
    :type capabilities: ~serviceswagger.models.DeviceCapabilities
    :param registration_id: Required. Registration ID.
    :type registration_id: str
    :param device_id: Desired IoT Hub device ID (optional).
    :type device_id: str
    :param registration_state: Current registration status.
    :type registration_state: ~serviceswagger.models.DeviceRegistrationState
    :param attestation: Required. Attestation method used by the device.
    :type attestation: ~serviceswagger.models.AttestationMechanism
    :param iot_hub_host_name: The Iot Hub host name.
    :type iot_hub_host_name: str
    :param initial_twin: Initial device twin.
    :type initial_twin: ~serviceswagger.models.InitialTwin
    :param etag: The entity tag associated with the resource.
    :type etag: str
    :param provisioning_status: The provisioning status. Possible values
     include: 'enabled', 'disabled'. Default value: "enabled" .
    :type provisioning_status: str or ~serviceswagger.models.enum
    :param created_date_time_utc: The DateTime this resource was created.
    :type created_date_time_utc: datetime
    :param last_updated_date_time_utc: The DateTime this resource was last
     updated.
    :type last_updated_date_time_utc: datetime
    """

    _validation = {
        'registration_id': {'required': True},
        'attestation': {'required': True},
    }

    _attribute_map = {
        'capabilities': {'key': 'capabilities', 'type': 'DeviceCapabilities'},
        'registration_id': {'key': 'registrationId', 'type': 'str'},
        'device_id': {'key': 'deviceId', 'type': 'str'},
        'registration_state': {'key': 'registrationState', 'type': 'DeviceRegistrationState'},
        'attestation': {'key': 'attestation', 'type': 'AttestationMechanism'},
        'iot_hub_host_name': {'key': 'iotHubHostName', 'type': 'str'},
        'initial_twin': {'key': 'initialTwin', 'type': 'InitialTwin'},
        'etag': {'key': 'etag', 'type': 'str'},
        'provisioning_status': {'key': 'provisioningStatus', 'type': 'str'},
        'created_date_time_utc': {'key': 'createdDateTimeUtc', 'type': 'iso-8601'},
        'last_updated_date_time_utc': {'key': 'lastUpdatedDateTimeUtc', 'type': 'iso-8601'},
    }

    def __init__(self, **kwargs):
        super(IndividualEnrollment, self).__init__(**kwargs)
        self.capabilities = kwargs.get('capabilities', None)
        self.registration_id = kwargs.get('registration_id', None)
        self.device_id = kwargs.get('device_id', None)
        self.registration_state = kwargs.get('registration_state', None)
        self.attestation = kwargs.get('attestation', None)
        self.iot_hub_host_name = kwargs.get('iot_hub_host_name', None)
        self.initial_twin = kwargs.get('initial_twin', None)
        self.etag = kwargs.get('etag', None)
        self.provisioning_status = kwargs.get('provisioning_status', "enabled")
        self.created_date_time_utc = kwargs.get('created_date_time_utc', None)
        self.last_updated_date_time_utc = kwargs.get('last_updated_date_time_utc', None)
