# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.service_client import SDKClient
from msrest import Configuration, Serializer, Deserializer
from .version import VERSION
from .operations.registry_operations import RegistryOperations
from . import models


class DeviceProvisioningServiceServiceRuntimeClientConfiguration(Configuration):
    """Configuration for DeviceProvisioningServiceServiceRuntimeClient
    Note that all parameters used to create this instance are saved as instance
    attributes.

    :param str base_url: Service URL
    """

    def __init__(
            self, base_url=None):

        if not base_url:
            base_url = 'https://localhost'

        super(DeviceProvisioningServiceServiceRuntimeClientConfiguration, self).__init__(base_url)

        self.add_user_agent('deviceprovisioningserviceserviceruntimeclient/{}'.format(VERSION))


class DeviceProvisioningServiceServiceRuntimeClient(SDKClient):
    """API for service operations with the Azure IotHub Device Provisioning Service

    :ivar config: Configuration for client.
    :vartype config: DeviceProvisioningServiceServiceRuntimeClientConfiguration

    :ivar registry: Registry operations
    :vartype registry: serviceswagger.operations.RegistryOperations

    :param str base_url: Service URL
    """

    def __init__(
            self, base_url=None):

        self.config = DeviceProvisioningServiceServiceRuntimeClientConfiguration(base_url)
        super(DeviceProvisioningServiceServiceRuntimeClient, self).__init__(None, self.config)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self.api_version = '2018-04-01'
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

        self.registry = RegistryOperations(
            self._client, self.config, self._serialize, self._deserialize)
