# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TwinCollection(Model):
    """TwinCollection.

    :param additional_properties: Unmatched properties from the message are
     deserialized this collection
    :type additional_properties: dict[str, object]
    :param version:
    :type version: long
    :param count:
    :type count: int
    :param metadata:
    :type metadata: ~serviceswagger.models.Metadata
    """

    _attribute_map = {
        'additional_properties': {'key': '', 'type': '{object}'},
        'version': {'key': 'version', 'type': 'long'},
        'count': {'key': 'count', 'type': 'int'},
        'metadata': {'key': 'metadata', 'type': 'Metadata'},
    }

    def __init__(self, **kwargs):
        super(TwinCollection, self).__init__(**kwargs)
        self.additional_properties = kwargs.get('additional_properties', None)
        self.version = kwargs.get('version', None)
        self.count = kwargs.get('count', None)
        self.metadata = kwargs.get('metadata', None)
